## import library

In [1]:
import numpy as np

## Create a numpy array 

In [2]:
numpy_array=np.array([1,2,3,4,5])
numpy_array

array([1, 2, 3, 4, 5])

## Create a Numpy array of Zeroes 

In [4]:
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Create a Numpy array of Ones

In [5]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Mathematical Operations on Numpy Array 

In [11]:
numpy_array1=np.array([1,2,3,4,5,6,7,8])
numpy_array2=np.array([1,1,1,1,1,1,1,1])

In [12]:
print(numpy_array1-numpy_array2)
print(numpy_array1+numpy_array2)
print(numpy_array1/numpy_array2)
print(numpy_array1*numpy_array2)

[0 1 2 3 4 5 6 7]
[2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8.]
[1 2 3 4 5 6 7 8]


## Indexing and Slicing on Numpy Arrays

In [13]:
numpy_array1[5]

6

In [14]:
numpy_array1[:5]

array([1, 2, 3, 4, 5])

In [15]:
numpy_array1[5:]

array([6, 7, 8])

In [36]:
numpy_array1[2:5]

array([3, 4, 5])

## Shape of Numpy Array

In [17]:
numpy_array1.shape

(8,)

## Change the shape of a Numpy Array

In [21]:
numpy_array_example=np.array([[1,2,3,4],[5,6,7,8]])
numpy_array_example

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
numpy_array_example.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [25]:
numpy_array_example.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## Stack Numpy Arrays

In [26]:
np.vstack((numpy_array1,numpy_array2))

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 1, 1, 1, 1, 1, 1, 1]])

## Stack Numpy Arrays along Column

In [27]:
from numpy import newaxis
np.column_stack((numpy_array1,numpy_array2))

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1],
       [5, 1],
       [6, 1],
       [7, 1],
       [8, 1]])

## Split Numpy Array

In [28]:
split_example=np.array([[1,2,3,4],[5,6,7,8]])
split_example

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
np.hsplit(split_example,4)

[array([[1],
        [5]]), array([[2],
        [6]]), array([[3],
        [7]]), array([[4],
        [8]])]

 The array has been split into 4 smaller arrays

## Copy Numpy Array

In [33]:
numpy_array1
numpy_array3 = numpy_array1           
numpy_array3 is numpy_array1

True

numpy_array3 and numpy_array1 both are same.  New object has not been created. 

In [35]:
numpy_array3=numpy_array1.copy()
numpy_array3

array([1, 2, 3, 4, 5, 6, 7, 8])

## Views in Numpy Array

In [34]:
numpy_array3 = numpy_array1.view()
numpy_array3 is numpy_array1

False